# Generated by Django 5.2.3 on 2025-06-27 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=9, verbose_name='CEP')),
                ('street', models.CharField(max_length=250, verbose_name='Rua')),
                ('number', models.CharField(max_length=20, verbose_name='Numero')),
                ('complement', models.CharField(blank=True, help_text='Ex: apto 33', max_length=250, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=250, verbose_name='Bairro')),
                ('city', models.CharField(max_length=150, verbose_name='Cidade')),
                ('state', models.CharField(help_text='Sigla do Estado, ex: RS, SC, SP, etc.', max_length=2, verbose_name='Estado')),
                ('country', models.CharField(default='Brasil', max_length=50, verbose_name='País')),
                ('is_primary', models.BooleanField(default=False, help_text='É seu endereço principal?', verbose_name='Endereço Principal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
