# Generated by Django 5.2.3 on 2025-06-27 11:56

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Número de Telefone'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='cpf',
            field=models.CharField(blank=True, help_text='Identidade do Usuario', max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
