# Generated by Django 5.2.3 on 2025-06-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel_birth_date_profilemodel_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='cpf',
            field=models.CharField(blank=True, help_text='Identidade do Usuario', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
