# Generated by Django 5.2.3 on 2025-07-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'MANUAL'), ('google_bookS', 'GOOGLE_BOOKS')], default='manual', max_length=20, verbose_name='fonte')),
                ('google_books_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID Google Books')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo do Livro')),
                ('publisher', models.CharField(blank=True, max_length=250, null=True, verbose_name='Editora')),
                ('published_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='Data de Publicação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numeros de Paginas')),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN-13')),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='ISBN-10')),
                ('thumbnail_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='URL da Capa')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço - R$')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo na Loja')),
                ('weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso (g)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Altura (cm)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Largura (cm)')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Comprimento (cm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='author_books', to='books.authormodel', verbose_name='Autores')),
                ('categories', models.ManyToManyField(related_name='category_books', to='books.categorymodel', verbose_name='Categorias')),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='books_bookm_title_5a4629_idx'), models.Index(fields=['isbn_13'], name='books_bookm_isbn_13_3919d0_idx'), models.Index(fields=['google_books_id'], name='books_bookm_google__ae024b_idx')],
            },
        ),
    ]
