# Generated by Django 5.2.3 on 2025-07-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookmodel_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='source',
            field=models.CharField(choices=[('manual', 'MANUAL'), ('google_books', 'GOOGLE_BOOKS')], default='manual', max_length=20, verbose_name='fonte'),
        ),
    ]
