# Generated by Django 5.2.3 on 2025-07-03 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_alter_bookmodel_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Aguardando Pagamento'), ('PROCESSING', 'Processando'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregue'), ('CANCELED', 'Cancelado'), ('FAILED', 'Falhou')], default='PENDING_PAYMENT', max_length=20, verbose_name='Status do Pedido')),
                ('shipping_address', models.TextField(verbose_name='Endereço de Entrega Completo')),
                ('total_items_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total dos Itens')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo do Frete')),
                ('shipping_method', models.CharField(blank=True, max_length=100, verbose_name='Metodo de Envio (ex: SEDEX)')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo de Rastreio')),
                ('melhor_envio_order_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Pedido no Melhor Envio')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Metodo de Pagamento')),
                ('payment_charge_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID de transação -AbacatePay-')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_title_snapshot', models.CharField(max_length=100, verbose_name='Titulo do Livro (no momento da compra)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (momento da compra)')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.bookmodel', verbose_name='Livro')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.ordermodel', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens dos Pedidos',
            },
        ),
    ]
