# Generated by Django 5.2.3 on 2025-07-03 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.addressmodel', verbose_name='Endereço de Entrega'),
        ),
    ]
