# Generated by Django 5.2.3 on 2025-07-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_ordermodel_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='payment_charge_id',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID da Intenção de Pagamento (Stripe)'),
        ),
    ]
