# Generated by Django 5.2.3 on 2025-07-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_ordermodel_payment_charge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='book_title_snapshot',
            field=models.CharField(max_length=255, verbose_name='Titulo do Livro (no momento da compra)'),
        ),
    ]
