# Generated by Django 5.2.3 on 2025-07-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitemmodel_book_title_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=255, verbose_name='Metodo de Envio (ex: SEDEX)'),
        ),
    ]
