# Generated by Django 5.2.3 on 2025-07-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_ordermodel_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID da Intenção de Pagamento (Stripe)'),
        ),
    ]
