# Generated by Django 5.2.3 on 2025-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_ordermodel_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='book_title_snapshot',
            field=models.CharField(max_length=500, verbose_name='Titulo do Livro (no momento da compra)'),
        ),
    ]
