# Generated by Django 5.2.3 on 2025-07-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitemmodel_book_title_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_service_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id do serviço de envio'),
        ),
    ]
