name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GOOGLE_BOOKS_API_KEY: ${{ secrets.GOOGLE_BOOKS_API_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
          ME_ACCESS_TOKEN: ${{ secrets.ME_ACCESS_TOKEN }}
          
          CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          DEBUG: ${{ secrets.DEBUG }}
          
          DB_ENGINE: ${{ secrets.DB_ENGINE }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: localhost 
          POSTGRES_PORT: 5432

          ME_CLME_CLIENT_ID: ${{ secrets.ME_CLME_CLIENT_ID }}
          ME_CLIENT_SECRET: ${{ secrets.ME_CLIENT_SECRET }}
          ME_SANDBOX_URL: ${{ secrets.ME_CLME_CLIENT_ID }}
          MY_STORE_ZIP_CODE: ${{ secrets.MY_STORE_ZIP_CODE }}
          MY_STORE_CITY: ${{ secrets.MY_STORE_CITY }}
          MY_STORE_STATE_ABBR: ${{ secrets.MY_STORE_STATE_ABBR}}
          MY_STORE_CPF: ${{ secrets.MY_STORE_CPF }}

        
        run: |
          echo "$FIREBASE_CREDENTIALS_JSON" > serviceAccountKey.json
          python manage.py migrate
          pytest
